apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: server-print-release
  namespace: flux-system
spec:
  interval: 1m
  install:
    remediation:
      retries: 2
  chart:
    spec:
      chart: server-print
      version: '0.1.1'
      sourceRef:
        kind: HelmRepository
        name: flux-test-project-helm-registry
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1

